name: Tests

on: [ push ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Display version
        run: |
          python -c "import sys; print(sys.version)"
          ls
      - name: Setup mongodb for tests
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: 8.0
          mongodb-port: 27018
          mongodb-username: root
          mongodb-password: example
          mongodb-db: calls

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install
      - name: Running tests
        run: |
          pytest


    

